export const AUTH_ENDPOINTS = {
    REGISTER: '/auth/register',
    LOGIN: '/auth/login',
    LOGOUT: '/auth/logout',
    FORGOT_PASSWORD: '/auth/forgot-password',
    RESET_PASSWORD: '/auth/reset-password',
    CHANGE_PASSWORD: '/auth/change-password',
    CONFIRM_EMAIL: '/auth/confirm-email',
    RESEND_CONFIRMATION: '/auth/resend-confirmation',
    REFRESH: '/auth/refresh',
    EXTERNAL_LOGIN: '/auth/external-login',
    OAUTH_CALLBACK: '/auth/oauth/callback',
    LINK_OAUTH: '/auth/oauth/link',
    LINKED_ACCOUNTS: '/auth/oauth/linked-accounts',
    UNLINK_OAUTH: (provider: string) => `/auth/oauth/unlink/${provider}`,
    ME: '/auth/me',
} as const;
